language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install django
  - pip install coverage
  - pip install coveralls
  - pip install django_nose
script:
  - coverage run --source track_actions --omit="*/migrations*" runtests.py
  - coverage report
after_success: coveralls