language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
addons:
  postgresql: 9.6

before_script:
  - psql -c 'CREATE DATABASE rest;' -U postgres
  - psql -c 'CREATE DATABASE test_db;' -U postgres

script:
  - python manage.py makemigrations app_test
  - python manage.py migrate app_test
  - python manage.py migrate track_actions
  - coverage run --source track_actions --omit="*/migrations*" runtests.py
  - coverage report -m

after_success: coveralls